steps:
# Build and push image to Google Container Registry (GCR)
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/fastapi-340818/flask-regression', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/fastapi-340818/flask-regression']
# Automatially update existing kubernetes services
- name: 'gcr.io/cloud-builders/kubectl' 
  args: [
   'rollout', 
   'restart', 
   'deployment/first-server'    # first-server the services that has been build before 
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=regression' # the cluster that has been build before 